version: '2'

services:
   db:
     image: mysql:5.7
     volumes:
       - "./.data/db:/var/lib/mysql"
       - "./.db_import:/docker-entrypoint-initdb.d"
     restart: always
     env_file:
       - "./.db-secret"

   nginx:
     depends_on:
       - drupal
     image: nginx:stable
     volumes:
       - "./nginx.conf.d:/etc/nginx/conf.d"
       - "./.data/files/kuradiauk:/usr/share/nginx/kuradiauk"
       - "./.data/files/pshortcut:/usr/share/nginx/pshortcut"
       - "./.data/files/root:/usr/share/nginx/root"
       - "./.data/files/aboutbears:/usr/share/nginx/aboutbears"
     links:
       - drupal
     restart: always
     # This part relies ssl_proxy project, which does all the work
     # on SSL certificates and proxies HTTPS traffic here.
     # See ssl_proxy_config.yml for more details.
     networks:
       - default
       - ssl_proxy_bridge_network

   drupal:
     depends_on:
       - db
       - postfix
     image: drupal:7.51-apache
     volumes:
       - "./.data/cms/myx:/var/www/html"
     links:
       - db
       - postfix
     restart: always

   postfix:
    image: marvambass/versatile-postfix
    volumes:
      - "./dkim:/etc/postfix/dkim"
      - "/var/log/postfix:/var/log"
    environment:
      DKIM_SELECTOR: blog
      POSTFIX_RAW_CONFIG_SMTPD_USE_TLS: 'no'
    command:
      - ostankin.net
      - 'mailer:${MAILER_PASSWORD}'
    restart: unless-stopped

networks:
  ssl_proxy_bridge_network:
    external: true
