#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DIR/common-functions
BACKUP_DIR=$BASE_BACKUP_DIR/latest
DB_IMPORT_DIR=.db_import
DATA_DIR=.data
DB_DIR=$DATA_DIR/db
DB_HOST=db
PWD_GEN_CMD='cat /dev/urandom | tr -dc A-Za-z0-9 | head -c${1:-32};echo;'
TIMESTAMP_CMD='date +%Y%j%H%M%S%N'

function drupal_replace_field {
  sudo sed -i -e 's/\('\'$2\''\s\+=>\s\+'\''\)[^'\'']*\('\''\)/\1'$3'\2/g' $1
}

function modx_replace_field {
  sudo sed -i -e 's/\('\$$2'\s\+=\s\+'\''\)[^'\'']*\('\''\)/\1'$3'\2/g' $1
}

function drupal_update_config {
  CMS_SETTINGS=$CMS_DIR/sites/default/settings.php
  sudo chmod u+w $CMS_SETTINGS
  drupal_replace_field $CMS_SETTINGS database $DB_NAME
  drupal_replace_field $CMS_SETTINGS username $USER_NAME
  drupal_replace_field $CMS_SETTINGS password $USER_PASSWORD
  drupal_replace_field $CMS_SETTINGS host $DB_HOST
  drupal_replace_field $CMS_SETTINGS prefix $TABLE_PREFIX
  sudo chmod a-w $CMS_SETTINGS
}

function modx_update_config {
  CMS_SETTINGS=$CMS_DIR/manager/includes/config.inc.php
  modx_replace_field $CMS_SETTINGS dbase $DB_NAME
  modx_replace_field $CMS_SETTINGS database_user $USER_NAME
  modx_replace_field $CMS_SETTINGS database_password $USER_PASSWORD
  modx_replace_field $CMS_SETTINGS database_server $DB_HOST
  modx_replace_field $CMS_SETTINGS table_prefix $TABLE_PREFIX
}

function generate_root_password {
  MYSQL_ROOT_PASSWORD=$(eval $PWD_GEN_CMD)
  echo "MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD" > $DB_SECRET
}

function generate_user_password {
  USER_PASSWORD=$(eval $PWD_GEN_CMD)
}

function check_backup {
  echo -n "Checking backup files for $1 ... "
  load_dumps
  if [ ! -f $MYSQL_DUMP ] || [ ! -f $CMS_DUMP ]; then
    echo
    echo "At least one of the following backup files are missing:"
    echo $MYSQL_DUMP
    echo $CMS_DUMP
    echo Exiting.
    exit 1
  else
    echo ok
  fi
}

function directory_is_empty {
  [ ! "$(ls -A $1)" ]
}

function restore_cms_files {
  echo -n "Restoring CMS files from $1 ... "
  CMS_DIR=$CMS_BASE_DIR/$BACKUP_NAME
  load_dumps
  sudo mkdir -p $CMS_DIR
  sudo tar -xzpf $CMS_DUMP -C $CMS_DIR
  generate_user_password
  USER_SQL=$DB_IMPORT_DIR/$($TIMESTAMP_CMD).sql
  cp $CREATE_USER_TEMPLATE $USER_SQL
  sed -i 's/#DATABASE#/'$DB_NAME'/g' $USER_SQL
  sed -i 's/#USERNAME#/'$USER_NAME'/g' $USER_SQL
  sed -i 's/#PASSWORD#/'$USER_PASSWORD'/g' $USER_SQL
  $CMS_NAME"_update_config"
  echo done
}

function load_mysql_container {
  MYSQL_CONTAINER=$(sudo docker ps -q -f ancestor=mysql:5.7)
}

function invoke_mysql {
  sudo docker exec -i $MYSQL_CONTAINER \
    mysql -u root --password=$MYSQL_ROOT_PASSWORD $1 2> /dev/null
}

function mysql_is_up {
  load_mysql_container
  echo "do 0;" | invoke_mysql
}

function restore_database {
  echo -n "Restoring database from $1 ... "
  load_dumps
  load_mysql_container
  echo "create database $DB_NAME;" | invoke_mysql
  zcat $MYSQL_DUMP | invoke_mysql $DB_NAME
  echo done
}

iterate_configs check_backup
echo "Restoring from backup will destroy current data. Type 'yes' to proceed."
read CHOICE
case "$CHOICE" in
  "yes")
    echo "Proceeding...";
    ;;
  *)
    echo "Exiting."
    exit
    ;;
esac

echo Bringing down and destroying existing containers...
sudo docker-compose down
sudo mkdir -p $DATA_DIR
sudo mkdir -p $CMS_BASE_DIR
sudo rm -r ${CMS_BASE_DIR?"Barmin prevented"}/*
mkdir -p $DB_IMPORT_DIR
chmod a+w $DB_IMPORT_DIR
directory_is_empty "$DB_IMPORT_DIR" || rm $DB_IMPORT_DIR/*
iterate_configs restore_cms_files
sudo rm -r ${DB_DIR?"Barmin prevented"}
generate_root_password
sudo docker-compose up -d
echo -n "Waiting for MySQL to start "
while ! mysql_is_up; do sleep 1; echo -n "."; done
echo " done"
iterate_configs restore_database
